install: gradle wrapper --gradle-version 4.9
language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
jdk:
- oraclejdk11
addons:
  sonarcloud:
    organization: com.github.jpmorganchase
    token:
      secure: "$SONAR_TOKEN"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
  - dev
  - "/.*/"
after_success:
- mvn deploy -Prelease-sign-artifacts --settings settings.xml
before_install:
- openssl aes-256-cbc -K $encrypted_81c98acad902_key -iv $encrypted_81c98acad902_iv
  -in codesigning.asc.enc -out codesigning.asc -d
env:
  global:
  - secure: Bqh4nOL1FiEqb3Z0scroFgBIvDxXptXoyZ4xmLgs7ic7hW3jqzyaubDu+cxBtj04XLjBTARvOGqgJ80fUmIaPZk9et1p8szayKWpC9sxqpLJhv6YHNQWWvl5HGar0KLitMQ0DamJtjgEfwqAGKuaJHeVtfEByoJnUEHtpgxcXYt94wHIn5av3EHRECHGExQ8kQe+ZwtIquYCaBnCLaPXZ88KRsJz1n+cFErYGDqT64K/K7mwQoao2Zwy3vJL8RMWAab9GndDszlbFYFsb7yRJNd6tvhDu0F+Td+p4LZ6YzvVn9bhXLbKSqUqXPzyVHrdrgaEmUKbVXERJJxAqVji6uEUV3UyNqB749aUiX6X+XQqvJ5++HNy+qDuSGeITkLuMBsyRQhJEEoeGa27PHqBWoo0RtpK9M21uU/k0O2tOAbeQOS4+ZRsSTOKM5eVYcdIh48i0XEDeehrEcfxCtTlUhcONSzsuVgKQm9gHbSPFAVoiR3We0UCaOeh1iBzC4JxeJGbVAwExnuAZKCs23XmCB2GMVs3l+tXegecJLva8+FMbrKtwdvs77NlfGTk/Ydzaf7lziv1uyhzmhS+tqTDeqKISpde2Bpq48uVjdvA3RvOeDbcWQUObZ51IQzuXIYyF5x2G8cdU7mDOLuBngSCRDMpP0/rH84H+js1t6+8EN4=
  - secure: P6pBKVggRNn9ZkP8cK6ty6ix1sGgEAK66bVfn+IfcSG+UE3lnwTTaw6lVpp/C+EOJsxAeLqBRVY8PpP/ZcvmPzTQ2GSJKdj5Mxv4JQldN1utzyIDubga0EA/7gQI3gn1cGKDqi4ddwwZMgKVV5SMTLgwg+5Jjz1foNcTJIglTCj7oNwOg4IGUwb4/hA+7wcTyGVymC0h4/xjFVLqxewfMQtsu0Cjvov/nX+fZC7iCWk12HwXfN0r/XNvFQEMMhjqwmUmAZX+QOB4PSQLL+1RByoxySUhiz5L4VhLfk9nc1NShG22yOSCKkMPb5l7SjKoCgLsCOqW+rgPBKTJkDQmFx2GQ6q5uxUfzOCwQAwZANzNSYpx+CmswpBOql6DzCN3v1i6ixwutmFz+JgQugJY0VthQmQVaOzMlNceoicdrxlm+9kaGrj3eaxT7Oj3JjuAN6D7sRI9bbDWxweWnKkHGf5UU+Tg/nqH/GwvmCdubRY8Pxc+hl05EbsiHWa8t5Je5SVVfaDw3lvB3K20DeO7CkDQMXX+VLz0EN94IHhXR4MfSk2zrgoDCmL7Lc1gP8jEEzTqpYFgNN8lyAIigMs/gTnCX8KKwzHwU4eNKtL8j3rHvreFalCXYDSxzohhznlD6PAPktTNv88oBw9R0OEonTTTAF0zO/X5xcftD/tpRQs=
  - secure: vJLWyk4IqZLjMLI4BVkhEblbfeE/EiGwkGnUQCq81q/ohfYhThoRHVUjBRB8t3Y+FkCwtjIrB4U8lOBO0wTYOCeBPiOEwFDch6kc/9ZvtfH4Dz8+2Vf5PPxfA433sM/YTgZJVa7j1dZu6Hz9D2JYPAjuiHEf3wycdxAmehZWjaGNjjYCoLvovg/D/ubyEm/rcKhwC9uZShLvWfvwaEqqyzMGYSdt+UiyG0zU67+4LBngQ9yKk3vgatloopa5agRbMsy537PZsz74XhoUC+wBDBQ9Rq8dLMak53X5fvhAcB//Z74SkQ3wvuPBfyOc5wbBXroFpSiIbqvSeMaORdhjqI8s7uCMnUvmL6bPkCvhvvQr2AqERPNl7saVvy+ZXHq8ozmhBhgn6+GG5c8tHRVunJFsVddnoxda8QOHX75gK/ZlAa9x89fBGoeno7eeXq/59yP054e4M8MQ+F2TYDlbD1XMYQenGdctzUtwQOKy0FsFsY+K/w0wb8f/QCpxkxmeqB26i8Iiwg3vt0ai0gf6YAkeJuYGZusgqFMIkis+uEhe1SrhSzmoV/UdzR9qXwRZkt28RYw9A6Hsovx8syC+be56EuxwWPUfiboBOsATH72NYraH4jDLMNdQ388Jntr2YtbZ3EE/92SdzV9C9u7M/6loVOTktXlMApAXTp6G+SA=
  - secure: STX+So5gceuPe91WCOJr5fSYnQ2Vs/JH88pyUluEwagszV3W6XiNhQ0kUZzrDxEMZSsWnK+Yx1A/KxEHd3S/emujUfaAw+qBxNSnJ+YLOqAammTBw4lJ85GN8vGEhZqLcWxfaLwv2IhhMJEoRvY9Iq3SY8rehzXcfUzvqH3rBrq1t9t9KUC9fgWg7s0AP/0IAwykzXt/SyteG4njwDu+HgG/MUdZkpwAgDdk6IKSul9pSEdo7YRP+C8huNgRvxPdZ0Mc53oil0kpGc0cjGe33kIARlMDnjAvJOYSMFBkUzwXandM0PhmNvqpiT5Ud9ptomAP/QugczhBD9sHdChS11BFcOGX7Lr7rlyQIhXwgZgh/wDx6ajfv2MoE49+fyN3ib+aN3sBxXb1E8kvcTtZdVDUDN8nGjyqOQA9ZMe6yZzjBVByX6xZ3+QrCkxTK4tCRexWhy5ndyZWIrRwX0ekuPutbHK67Amv3Gr2H9uQbJ79MFhPf8/df7gHAW3IHzL65cDq+clHoG3rFjQsJR2tgCSw9N5s2FKGh6Ex02ckKkwMGcagYvtBaKav7ZzrqHyNih/L9+bgGmAfBG8N1VA7ZhJX5eazi7nW4IsmecvCD1u563AGmOSGNlCl4LmSKNRrwbmtqtd0pjtaCNLWtEmnnsfR6DTDdp+1y1KTiC9xS54=
