install: gradle wrapper --gradle-version 4.9
language: java
jdk:
- oraclejdk11
env:
  global:
    secure: C92gwH3a6zvc6/KQ8bhSD9rGbhg6cCey78WQ9Qbvf1t+ON/7UK8RLHtIyYbOCH9q8PLm21eAflqSYi9giA87UvNcUOfOIin0WXxHkJnUhjkHKElL+n2jhVkaEtRmJdUkP3T304jo72bDAAP8adoBbtAvjugE6raC7ra8EjIaRUpLrne2cmQGEYW83zDTYl8M1DRWTGNJQXkC3ZCR4dD40fzfITLoHn5GYmrG0mKguiurvateML/xGH9TWKGzDLz19PTB3Y1+EKjELmkLKXzTgdYU8ZmdOMpzm126y/1z67zCpATNRvldIH+WXgLzd8ZxnomvNA7zSFxlGpD4dqhxBYb9pbsoDe7S4f6rSBkqbzSv/kPm8Acbfn5YyGtMVxXWgGp5qUma+O+k3RZGjLNV7HMpoo0s6KAXxMRp3L7TdzxXuLbu4CGEUPFkZyxW3vngMXRd45DhBi49xxq730jINBtTr2Tlru8EVdQnLwgjCSzizuKtD0qAQAqXKgKNDZYBQopM0KVwgReRsrvPFjYyAtDTnx4gFl2kbTxzC4VdjuKeIYluNU8vO2mvXa6dVJQzJdi5ZGWeyg0GJjYEWXXJcTMo0LG2+WQHV9ztogqpDG1v+Q+CERPvIKg5jAmguJfIwxphqqqQLXPH04u5yMLGIzISuSoL+OzxYrjGPFAZCe0=
