install: gradle wrapper --gradle-version 4.9
language: java
before_deploy:
- mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
- export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep
  -v '\[')
jdk:
- oraclejdk11
addons:
  sonarcloud:
    organization: com.github.jpmorganchase
    token:
      secure: "$SONAR_TOKEN"
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
branches:
  only:
  - master
  - dev
  - "/.*/"
after_success:
- mvn deploy -Prelease-sign-artifacts --settings settings.xml
before_install:
- openssl aes-256-cbc -K $encrypted_81c98acad902_key -iv $encrypted_81c98acad902_iv
  -in codesigning.asc.enc -out codesigning.asc -d
env:
  global:
  - secure: CL/OXw0oOFui9ku79exJAstu6f4d0T9NsjnAHmdpjL/aohvJ52JvA4FpW1Vi82wys17mrerXUPm+Cuo05HZ1zP1OSBuFfQpWepYsbjVxn2growTb4z+ECABSAGscA2PcPdzlmO7YIpwIs2nGmM1Nwgvytvij0YbHqts8p+XLZzhx2YU1H6j17KVpuOMDF3Gt9H+gQQ0a8D2XIIfRqUaaU2q75x67+nyKNrxbggrvVLlDHwzfdRiBkMvzl9hWUXd/Jw31NMmONdnn7RuagGmaCSW3qx6qluHDu88DhVOKCnS5+DoDkZqfFwno4XVerxjgOr4br3sEeOK1pJy0SWrFc4UGyMkLLm2vxSKoLh1y9jv84iPgbdAYOPdzDDsSLVm15uNz2KW67v3sZN3mj7KzRd2NuvEnOkKDgWQoBeTF7g8ZfE2ARM4OLHrmV2u5LYRb01uPUcFf8bLATWPRowb1SKMdfTqLyQBz2/vQQtbpx7nTBZtXInaXYe8fL3K3n+E0FlIhWWu81mUFCmXcvdA0y5mN7PBptbPz/iEUErKit1nup2+OxzAtkCpMmdTjGuE8qqnTtrbhfCreOOdCIbbY8JBW9I7qahOJTsqqlGYJbAlTfVQ5n1OfTOjzjfh5BXAx36neMXP1Ye/Mb+BthNPvGj6kIxQJC3LHNDeiFuSj2EE=
  - secure: jZ4CtiErFh0zHpmjwFhEYDVlIjhyOVCmEdZ2U4sKZQ3GXel/a9dPk1Rsbk43xu7pctRLZTr9jFIE9q/YP3/NhYCQUFJdGbjIj/a2ty5js/HDSm3Pp9YEMjzeeuIxkgmcx4hYQ3dWqje/7aW6Ya9b7R9aH8AGlWJ/xjchnA/8k3NKbARz6TQbgbFgHdp6FnE/g3A/CSEv7uIl2MAbZ4Cb9dogilhwOdVfitfFCf8Lg0uwYamgGQLTOAzpOKsPfMpsLMq5+8ws6p7ws8K36hUe4HrNlxK7W1+9iVt1GG4giFFjAljPm/RW1KLCLV3Oac8bjFGNB2ZerdC5KXFTXuoA5Sia3exNvdhCpQ72BhR8kVKaNUixaSLTSJWSk/S+3mVXtYCu9boaApVJntnDZUX5b4/ARb7gIcGq3pFXD28mHheMBgqnBaVJUn7C86OqLb5ppK5OnNEjh/B60HAWu8XzdEcmsHVCbmQN4jtTnBOI+o68DnKv3/CIjKgLBQe6F3zHJWtPjtOAiwqsJQU4Uc35nv3SEHjZK5YQgBvHXYMsHuF5AB3+IyVMsqHWKB94Ita/EdjHll3/xSOJzC4Ctf8AANb2XcQ7rKh7m2PMSPULTmCnOBWiYb06gg7DJoNsYRPjRZuWEkVZQoVik6fEb0kgM77Myjsf/U2RWy7TCC/f8WM=
  - secure: r8QzVL6xRSczHmHzCaEBFoKVleJT1qut1HFmlal/kZq1xPY1wsDMMBmNgHD3zYq2nn8+nQGN15V38h51LqgtFYZbUTvT38rsrS0/0aikPUT4ut6v9GbVs3X1Ae1YDYKudowPc/70hMr6JS8U3PB7HXOmV5SeUzg9/7XOmhhHLoFr3/ncu4ZL2utx6rW71vokcc2R0RhcjSrd0UvYveCYa0rTCgB0ZK3D4VggMnfvQQckK0CAMWtAvW8pD5mRO8V/Y5hTISfqLZSJqF30xXxZhUHJETeSYRf/IV+vWDbayZvkptKRN7R0h4n9jT6ixQjqQUXSH2a7Ds4PdkaqXG62zVBRqyX+Ezhronp33NwW5d0lHemVIkAE695smZktC/5D6ggQkFEepNT6jAz/Je3vppBy5T5ffq1CHy2q013pxNz3088oQFk/kfYcwLIaxg+++CDzkZaoxi2wCtpjU3J/XKvZ+P9GG1lXQRC2MVsZ7pi1d/91D6JI8qOs/CJlYOwcNfEH0iVfu7wmwdFqJe/RRqUJ+9Tv5R9VEucloiiIt30dDNX276/AjpZL9S1kjpW+FKxGh+Fz9vjsWpDqOnPTejUQexMWUHxL2aACAzle33o92LstxP2Dd0gYcLvD/Dh5gxLRvNHVOe8Yc3g0akL1C/mKxSY09/ziy4d+qAoRVWM=
  - secure: qwgEHbyJjCWBeIfuCZN0vQZq5aAWLQL3qVtSKMwwLJGbWGItNxSlQraA/sTMXDlRXJcFxZSZ7XlJs+d4iQMZTuWFsCtwyPk7MjI2s6CPImjAZvuNYYZlSeNzmobXMZSZ5/FCtvDJ0sI0xZ0Wie1t3sMOomLkzKS396mnLI0nRJe9coV8GFWB+8uwGXf6dnoOS4snBGhITtVURPe7rAgxVG5yqIqFym/g6wFzIAET5tF21jzvlVrMXqR03232ebXkvkj/bhM1FwD/uXvzGr59UH9SdlGCJKCqLGyXk336lhNm2+NJrGxs2Qju8JxJ4LhQtY9fmbgpw04FPGL32dGH/q+hiJ1WRp2DxfDp4UUBcZeEWv5sQDBYdtJxq6U8rSDYMRTZCr3/vfDvZcGPhjfY7bWu5SHpmYd1UPVc32NMhxbeHe6roksm8zDxDub8vcyXNhNfptxBkVMCPMWujH8HwoRAhJ6Dt2DaIScsQCvi5BJDd17+CWsOaSBHcO4YdR646DliwzUn2+0CxDbmv1ryuWxrpZtjMw2fBrdX5PB13Lpow7PrbcMTltkdK/2SZo34rmSLnPoaSyOBSX8/iS/o47OagwtmqEBO+sxi6E67aKEZQUFY4/WHsgnA4Coa2A8If5SOK0DxCQD+gUfVrwFMOMVTZt0eTepoPYrnJiVAXoc=
