before_deploy:
  - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
sudo: false
language: java
cache:
  directories:
  - "$HOME/.cache"
deploy:
  provider: releases
  api_key:
    secure: oBa19uq0ZxzJ2Gip3+gheXDdcsxuyJRP3y3dyJfT9P8KnLrlTKpd0ICDeXOsWWIBNs+QhKVKErXzDiooQ6QxbQvpNZx2qr0ZrDMF9iEF6n9HKcJSNIrzr+R9CbzLNB1ArkUQxsld2X9i9QJR/UGqM7IxrkoJTGRh2X1eXvf3cDTNTkkGXw8CKUPwU9kqJ4Uyryq+pvS5xIf9zGBQO3Kvy3KZB3IcPQnxgQd65Tyzliyb//Tu7SODIFlZNS58/B8Zd38APts+LOcjtIfVw7U5GT97EYBviAy/6i9PRj9HgSxQW6Mre1f/jafqK8hgZVgzyvkfyMjqg+8Gb2zqCfoK8UFK1yKtLESLvLFRPPCnIgpmqTYIP912aRUAYYhpQiCtZoMJPahNzPmFgeVeD3bovd4yFIm6QhjQkRzacyraXVYXSuS/4WAXSafaBYiEbKTkq0zV+exc7GocaA3R5nTKd+NanZmKTk67U+KyF6gRG5X0VCvu/u3bCfkyR/vNTaAd89G7xKH4ox8FVYL2NIX21zYjvumKbp292bOGUbAQP3wwkFBqq+Fq3I6+OJ1XlwXbOahY/B4QxzCmdg9nIiVoVvfJjkeToq7Wu8AsA6bz2hRbaPcUxcctK0Xcb7QM/vHA4s+OL7trcqGevdjUfhA015UXpodRHuyu1HKuqvytVIM=
  file: ''
  skip_cleanup: true
  on:
    repo: jpmorganchase/java-lint-assert
  name: $project_version  
notifications:
  email:
    recipients:
    - an.nadein@jpmchase.com
    on_success: change
    on_failure: always
